-- Phân quyền cho khách hàng
GRANT EXEC ON SP_GET_DONGHO_KH TO KHACHHANG
GRANT EXEC ON SP_THEM_CT_PHIEU_DAT TO KHACHHANG
GRANT EXEC ON SP_THEM_PHIEU_DAT TO KHACHHANG
GRANT EXEC ON SP_TIM_KIEM_DH TO KHACHHANG
GRANT EXEC ON SP_DOI_MATKHAU TO KHACHHANG

USE master
CREATE USER [HTRS] FOR LOGIN [HTRS] WITH DEFAULT_SCHEMA=[dbo]
ALTER ROLE [db_owner] ADD MEMBER [HTRS]
ALTER SERVER ROLE [dbcreator] ADD MEMBER [HTRS]

